language: php
dist: trusty
sudo: required

php:
    - 5.6

before_script:
   - sudo add-apt-repository -y ppa:ondrej/php5-5.6
   - "sudo add-apt-repository -y \"deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse\""
   - "sudo add-apt-repository -y \"deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe multiverse\""
   - sudo apt-get update
   - sudo apt-get install -y --force-yes mysql-server apache2 libapache2-mod-fastcgi php5-fpm libapache2-mod-php5 php5-gd php5-json php5-curl php5-mysql php5-intl php5-mcrypt
   # enable php-fpm
   - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
   - sudo a2enmod rewrite actions fastcgi alias
   - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm --version
   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
   # configure apache virtual hosts
   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   - sudo service apache2 restart
   - curl 127.0.0.1
   - cat *.log
